--#SET TERMINATOR @

CREATE PROCEDURE TRANSACTION_ROSE

LANGUAGE SQL
MODIFIES SQL DATA

BEGIN
	
		DECLARE SQLCODE INTEGER DEFAULT 0;
		DECLARE RETCODE INTEGER DEFAULT 0;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		SET RETCODE = SQLCODE;
		
		UPDATE BANKACCOUNTS
		SET BALANCE = BALANCE-200
		WHERE ACCOUNTNAME = 'Rose';
		
		UPDATE BANKACCOUNTS 
		SET BALANCE = BALANCE+200
		WHERE ACCOUNTNAME = 'Shoe Shop';
		
		UPDATE SHOESHOP
		SET Stock = Stock - 1
		WHERE Product = 'Boots';
		
		UPDATE BANKACCOUNTS
		SET BALANCE = BALANCE - 300
		WHERE ACCOUNTNAME = 'Rose';
		
		IF RETCODE < 0 THEN
			ROLLBACK WORK;
			
		ELSE 
			COMMIT WORK;
			
		END IF;
		
END
@

		