--#SET TERMINATOR @

CREATE OR REPLACE PROCEDURE TRANSACTION_JAMES

LANGUAGE SQL
MODIFIES SQL DATA

BEGIN
	
		DECLARE SQLCODE INTEGER DEFAULT 0;
		DECLARE RETCODE INTEGER DEFAULT 0;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		SET RETCODE = SQLCODE;
		
		UPDATE BANKACCOUNTS
		SET BALANCE = BALANCE-900
		WHERE ACCOUNTNAME = 'James';
		
		UPDATE BANKACCOUNTS 
		SET BALANCE = BALANCE+900
		WHERE ACCOUNTNAME = 'Shoe Shop';
		
		UPDATE SHOESHOP
		SET Stock = Stock - 3
		WHERE Product = 'Trainers';
		
		UPDATE BANKACCOUNTS
		SET BALANCE = BALANCE - 150
		WHERE ACCOUNTNAME = 'James';
		
		IF RETCODE < 0 THEN
			ROLLBACK WORK;
			
		ELSE 
			COMMIT WORK;
			
		END IF;
		
END
@

		